# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation



# 1. Files excluded from Jekyll builds
# don't know why these are excluded to start with but they seem to break it?
# Keep in for now.
# exclude:
# - README.md
# - CODE_OF_CONDUCT.md
# - CONTRIBUTING.md
# - screenshot.png
# - LICENSE
# - CNAME
# - Gemfile
# - Gemfile.lock
# - alembic-jekyll-theme.gemspec

# 2. Installed Gems
# Not sure what most of these plugins do but they don't seem to break anything soooooo
markdown: kramdown
remote_theme: daviddarnes/alembic
plugins:
 - jekyll-feed
 - jekyll-remote-theme
 - jekyll-sitemap
 - jekyll-remote-theme
 - jekyll-mentions
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-default-layout
 - jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page



# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Los_Angeles # Timezone for blog posts and alike


# Don't know  what these do either
# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: |
      Thoughts on science and programming
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "https://picsum.photos/2560/600?image=866" # Default image for sharing




# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Umihiko Hoshijima" # Site name or title, also used in jekyll-seo-tag
#logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: Umihiko Hoshijima - Ecophysiology and environmental variability in an era of global change"
 # Site description and default description, also used in jekyll-seo-tag
url: "umihoshijima.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/umihoshijima/umihoshijima.github.io"
email: "uhoshiji@ucsc.edu"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
google_analytics: 'UA-76455894-1'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference



# 8. Site navigation
navigation_header:
  Home: /
  Research: /research/
  Publications/CV: /pubs_cv/
  Blog: /blog/
  #Categories: /categories/
  #Search: /search/
  #Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Umihiko Hoshijima

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/umihoshijima
  LinkedIn: https://www.linkedin.com/in/umihiko-hoshijima-30217892/
  #Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/umihoshijima
  link: https://www.hoshijima.org
#  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
